admin_slide_index:
    path:     /
    defaults: { _controller: "CommonCarouselBundle:Slide:index" }
    methods:  GET

admin_slide_show:
    path:     /{id}/show
    defaults: { _controller: "CommonCarouselBundle:Slide:show" }
    methods:  GET

admin_slide_new:
    path:     /new
    defaults: { _controller: "CommonCarouselBundle:Slide:new" }
    methods:  [GET, POST]

admin_slide_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommonCarouselBundle:Slide:edit" }
    methods:  [GET, POST]

admin_slide_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommonCarouselBundle:Slide:delete" }
    methods:  DELETE
