test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /test

app_back:
    resource: "@AppBackBundle/Resources/config/routing.yml"
    prefix:   /

app_front:
    resource: "@AppFrontBundle/Resources/config/routing.yml"
    prefix:   /

common_user:
    resource: "@CommonUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
common_carousel_slide:
    resource: "@CommonCarouselBundle/Controller/SlideController.php"
    type:     annotation

common_carousel:
    resource: "@CommonCarouselBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

